[tool.poetry]
name = "pharmachat-frontend"
version = "0.1.0"
description = ""
authors = ["Ramon Botella Nieto <rbnieto@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.41.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
